version: "3"
services:
  cli:
    build:
      context: .
      dockerfile: cli.Dockerfile
    image: devenv-cli
    container_name: "$DEVENV_NAME-cli"
    tty: true
    volumes:
      - $DEVENV_WORKDIR:/app
    user: "${DEVENV_UID}:${DEVENV_GID}"
  maven:
    build:
      context: .
      dockerfile: maven-ibmjava.Dockerfile
    image: devenv-ibmjava-maven
    container_name: "$DEVENV_NAME-maven"
    tty: true
    volumes:
      - $DEVENV_WORKDIR:/app
      - $DEVENV_M2:/.m2
    user: "${DEVENV_UID}:${DEVENV_GID}"
  git:
    build:
      context: .
      dockerfile: git.Dockerfile
    image: devenv-git
    container_name: "$DEVENV_NAME-git"
    tty: true
    volumes:
      - $DEVENV_WORKDIR:/app
    user: "${DEVENV_UID}:${DEVENV_GID}"
