#!/bin/sh

Start() {
  docker-compose up -d
}

Stop() {
  docker-compose down
}

Status() {
  docker-compose ps
}

Cli() {
  if [ "$#" -eq 0 ]; then
    docker-compose exec cli /bin/sh
  else
    docker-compose exec cli "$@"
  fi
}

Git() {
  if [ "$#" -eq 0 ]; then
    docker-compose exec git git --help
  else
    docker-compose exec git git "$@"
  fi
}

Mvn() {
  if [ "$#" -eq 0 ]; then
    docker-compose exec maven mvn --help
  else
    docker-compose exec maven mvn "$@"
  fi
}

Start
